
name: 'Build Css'
description: 'Build Css'

# outputs:
#   css:
#     description: 'Css Data'

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

runs:
  using: 'node12'
  main: 'build.js'
